// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuoukxcvwrbssqoqmquk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1b3VreGN2d3Jic3Nxb3FtcXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMjkwNDgsImV4cCI6MjA4ODYwNTA0OH0.pKbVkHC1p-b2W6oCsb04QtaAl7Peal0Ymae2SahRM8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});